routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/', 'IndexController@index');
Route::match(['get', 'post'], '/adminLogin', 'AdminController@login')->name('admin.login');

//Password reset routes
Route::post('admin/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::get('admin/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::post('admin/password/reset', 'Auth\ResetPasswordController@reset')->name('admin.password.update');
Route::get('admin/password/reset/{token}','Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');

Route::group(['as'=>'admin.' ,'middleware' => 'auth', 'prefix'=>'admin'], function(){
    // Admin Settings and Login
    Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');
    Route::get('/admin/profile/{id}', 'AdminController@profile')->name('profile');
    Route::post('/admin/update/profile/{id}', 'AdminController@updateProfile')->name('update.profile');
    Route::match(['get', 'post'], '/admin/edit/password', 'AdminController@editPassword')->name('edit.password');
    Route::post('/admin/edit/check-password', 'AdminController@chkUserPassword');

    //Categories
    Route::get('category/create', 'CategoryController@create')->name('category.create');
    Route::get('category/view', 'CategoryController@view')->name('category.view');
    Route::post('category/store', 'CategoryController@store')->name('category.store');
    Route::match(['get','post'],'edit-category/{id}','CategoryController@edit')->name('category.edit');
    Route::match(['get','post'],'delete-category/{id}','CategoryController@delete')->name('category.delete');
    Route::match(['get','post'],'trash-category/{id}','CategoryController@trash')->name('category.trash');

    //Jobs
    Route::match(['get','post'],'job/create','JobController@addJob')->name('job.create');
    Route::match(['get','post'],'job/view-jobs','JobController@viewJobs')->name('job.view');
    Route::match(['get','post'],'edit-job/{id}','JobController@edit')->name('job.edit');
    Route::match(['get','post'],'/delete-job/{id}','JobController@delete')->name('job.delete');
    Route::match(['get','post'],'delete-job-image/{id}','JobController@deleteJobImage')->name('job.image.delete');


    // Route::match(['get','post'],'trash-job/{id}','JobController@trash')->name('job.trash');











});



Route::get('/logout', 'AdminController@logout')->name('admin.logout');


Route::get('/home', 'HomeController@index')->name('home');

// Categories
// Route::group(['as'=>'admin.', 'middleware'=>['auth', 'admin'] , 'prefix'=>'admin'],function(){



// });

resources/views/admin/admin_login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{asset('public/adminpanel/images/fab.png')}}">

    <title>{{ config('app.name', 'Laravel') }} - Log in </title>

    <!-- Bootstrap 4.0-->
    <link rel="stylesheet" href="{{asset('public/adminpanel/assets/vendor_components/bootstrap/dist/css/bootstrap.min.css')}}">

    <!-- Bootstrap extend-->
    <link rel="stylesheet" href="{{asset('public/adminpanel/css/bootstrap-extend.css')}}">

    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('public/adminpanel/css/master_style.css')}}">

    <!-- NeoX Admin skins -->
    <link rel="stylesheet" href="{{asset('public/adminpanel/css/skins/_all-skins.css')}}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body class="hold-transition bg-img" style="background-image:url({{asset('public/adminpanel/images/login-bg.jpg')}})" data-overlay=5>

<div class="container pt-3 h-p100">
    <div class="row h-p100 justify-content-sm-center align-items-center">
        <div class="col-sm-6 col-md-4">

            <div class="card border-info text-center">
                <div class="card-header">
                </div>
                <div class="card-body">
                    <img src="{{asset('public/adminpanel/images/login-top.png')}}" class="img-fluid w-150 mb-10">
                    <h4 class="text-center mb-20">{{ config('app.name', 'Laravel') }}</h4>
                    <div id="loginbox">
                        @if(Session::has('flash_message_error'))
                            <div class="alert alert-error alert-block">
                                <button type="button" class="close" data-dismiss="alert" style="color: white;">
                                    <i class="fa fa-close"></i>
                                </button>
                                <strong>{!! session('flash_message_error') !!}</strong>
                            </div>
                        @endif
                        @if(Session::has('flash_message_success'))
                            <div class="alert alert-info alert-block">
                                <button type="button" class="close" data-dismiss="alert" style="color: white;">
                                    <i class="fa fa-close"></i>
                                </button>
                                <strong>{!! session('flash_message_success') !!}</strong>
                            </div>
                        @endif
                    </div>
                    <form action="{{route('admin.login')}}" method="post" class="form-signin">
                        @csrf
                        <input type="email" class="form-control mb-2" placeholder="Email" required autofocus name="email" id="email">
                        <input type="password" class="form-control mb-2" placeholder="Password" required name="password" id="password">
                        <button class="btn btn-lg btn-primary btn-block mb-20" type="submit">Sign in</button>
                        <div class="checkbox float-left">
                        </div>
                        <a href="" class="float-right">Forgot Password</a>
                    </form>
                </div>
            </div>
            <a href="{{route('admin.password.request')}}" class="float-right text-white">Forgot Your Password</a>
        </div>
    </div>
</div>


<!-- jQuery 3 -->
<script src="{{asset('public/adminpanel/assets/vendor_components/jquery/dist/jquery.min.js')}}"></script>

<!-- popper -->
<script src="{{asset('public/adminpanel/assets/vendor_components/popper/dist/popper.min.js')}}"></script>

<!-- Bootstrap 4.0-->
<script src="{{asset('public/adminpanel/assets/vendor_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>

</body>
</html>

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.admin_design')
@section('title')
    <title>Dashboard - {{ config('app.name', 'Laravel') }}</title>
@endsection

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="box">
                        <div class="row no-gutters py-2">

                            <div class="col-sm-6 col-lg-3">
                                <div class="box-body br-1 border-light">
                                    <div class="flexbox mb-1">
						  <span>
							<i class="ion-person font-size-26"></i><br>
							New Users
						  </span>
                                        <span class="text-primary font-size-40">34</span>
                                    </div>
                                    <div class="progress progress-xxs mt-10 mb-0">
                                        <div class="progress-bar" role="progressbar" style="width: 35%; height: 4px;" aria-valuenow="35" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>


                            <div class="col-sm-6 col-lg-3 hidden-down">
                                <div class="box-body br-1 border-light">
                                    <div class="flexbox mb-1">
						  <span>
							<i class="ion-document font-size-26"></i><br>
							Today Invoices
						  </span>
                                        <span class="text-info font-size-40">18</span>
                                    </div>
                                    <div class="progress progress-xxs mt-10 mb-0">
                                        <div class="progress-bar bg-info" role="progressbar" style="width: 55%; height: 4px;" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>


                            <div class="col-sm-6 col-lg-3 d-none d-lg-block">
                                <div class="box-body br-1 border-light">
                                    <div class="flexbox mb-1">
						  <span>
							<i class="ion-information font-size-26"></i><br>
							Open Issues
						  </span>
                                        <span class="text-warning font-size-40">46</span>
                                    </div>
                                    <div class="progress progress-xxs mt-10 mb-0">
                                        <div class="progress-bar bg-warning" role="progressbar" style="width: 65%; height: 4px;" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>


                            <div class="col-sm-6 col-lg-3 d-none d-lg-block">
                                <div class="box-body">
                                    <div class="flexbox mb-1">
						  <span>
							<i class="ion-folder font-size-26"></i><br>
							New Projects
						  </span>
                                        <span class="text-danger font-size-40">12</span>
                                    </div>
                                    <div class="progress progress-xxs mt-10 mb-0">
                                        <div class="progress-bar bg-danger" role="progressbar" style="width: 40%; height: 4px;" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>

        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/admin/edit_password.blade.php
@extends('admin.layouts.admin_design')

@section('title')
    <title>Profile - {{ config('app.name', 'Laravel') }}</title>
@endsection

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Password Settings
            </h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i class="iconsmind-Library"></i></a></li>
                <li class="breadcrumb-item"><a href="javascript:">Admin</a></li>
                <li class="breadcrumb-item active">Change Password</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Basic Forms -->
            <div class="box box-solid box-info">
                <div class="box-header with-border">
                    <h6 class="box-subtitle text-white">Change Password</h6>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="col">
                            <form action="" method="post" enctype="multipart/form-data">
                                @csrf

                                <input type="hidden" name="email" value="{{Auth::guard('web')->user()->email}}">
                                <div class="form-group">
                                    <h5>Current Password<span class="text-danger">*</span></h5>
                                    <div class="controls">
                                        <input type="password" name="current_password" id="current_password" class="form-control" data-validation-required-message="This field is required" >
                                        <p style="color: red; margin-bottom: 0px;">{{ $errors -> first('correct_password') }}</p>
                                        <b><p id="correct_password" style="color: green;"></p> </b>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <h5>New Password<span class="text-danger">*</span></h5>
                                    <div class="controls">
                                        <input type="password" name="new_password" id="new_password" class="form-control"  data-validation-required-message="This field is required" > </div>
                                </div>

                                <div class="form-group">
                                    <h5>Confirm Password<span class="text-danger">*</span></h5>
                                    <div class="controls">
                                        <input type="password" name="confirm_password" id="confirm_password" class="form-control"  data-validation-required-message="This field is required" data-validation-match-match="new_password"> </div>
                                </div>




                                <div class="text-xs-right">
                                    <button type="submit" class="btn btn-info">Update Password</button>
                                </div>
                            </form>

                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection


@section('scripts')

    <script type="text/javascript">
        @if(session('flash_message'))
        swal("Success!", "{!! session('flash_message') !!}", "success")
        @endif
    </script>

    <!-- Form validator JavaScript -->
    <script src="{{asset('public/adminpanel/js/pages/validation.js')}}"></script>
    <script>
        ! function(window, document, $) {
            "use strict";
            $("input,select,textarea").not("[type=submit]").jqBootstrapValidation();
        }(window, document, jQuery);
    </script>



    {{--Check current password--}}
    <script>
        $("#current_password").keyup(function(){
            var current_password = $("#current_password").val();
            // alert(current_password);
            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                type:'post',
                url:'check-password',
                data:{current_password:current_password},
                success:function(resp){
                    // alert(resp);
                    if(resp=="false"){

                        $("#correct_password").text("Entered value does not match the current password").css("color","red");

                    }else if(resp=="true"){

                        $("#correct_password").text("Current password matched").css("color","green");
                    }
                },error:function(resp){

                }
            });
        });
    </script>




@endsection

@section('styles')
    <style>
        .error{
            color: red;
        }
    </style>
@endsection

resources/views/admin/profile.blade.php
@extends('admin.layouts.admin_design')

@section('title')
    <title>Profile - {{ config('app.name', 'Laravel') }}</title>
@endsection

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                My Profile
            </h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}"><i class="iconsmind-Library"></i></a></li>
                <li class="breadcrumb-item"><a href="javascript:">Admin</a></li>
                <li class="breadcrumb-item active">My Profile</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Basic Forms -->
            <div class="box box-solid box-info">
                <div class="box-header with-border">
                    <h6 class="box-subtitle text-white">Profile Details</h6>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="col">
                            <form action="{{route('admin.update.profile', $user->id)}}" method="post" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group">
                                    <h5>Name<span class="text-danger">*</span></h5>
                                    <div class="controls">
                                        <input type="text" name="name" id="name" class="form-control" data-validation-required-message="This field is required" value="{{$user->name}}"> </div>
                                </div>

                                <div class="form-group">
                                    <h5>Email<span class="text-danger">*</span></h5>
                                    <div class="controls">
                                        <input type="email" name="email" id="email" class="form-control"  data-validation-required-message="This field is required" value="{{$user->email}}"> </div>
                                </div>

                                <div class="form-group">
                                    <h5>Image</h5>
                                    <div class="controls">
                                        <input type="file" name="image" class="form-control"> </div>
                                    <br>
                                    <input type="hidden" name="current_image" value="{{$user->image}}">
                                    <img src="{{asset($user->image)}}" alt="{{$user->name}}" width="100px">
                                </div>



                                <div class="text-xs-right">
                                    <button type="submit" class="btn btn-info">Update</button>
                                </div>
                            </form>

                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection


@section('scripts')
    <!-- Form validator JavaScript -->
    <script src="{{asset('public/adminpanel/js/pages/validation.js')}}"></script>
    <script>
        ! function(window, document, $) {
            "use strict";
            $("input,select,textarea").not("[type=submit]").jqBootstrapValidation();
        }(window, document, jQuery);
    </script>


    <script type="text/javascript">
        @if(session('flash_message'))
        swal("Success!", "{!! session('flash_message') !!}", "success")
        @endif
    </script>
@endsection