routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/', 'IndexController@index');
Route::match(['get', 'post'], '/adminLogin', 'AdminController@login')->name('admin.login');

//Password reset routes
Route::post('admin/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::get('admin/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::post('admin/password/reset', 'Auth\ResetPasswordController@reset')->name('admin.password.update');
Route::get('admin/password/reset/{token}','Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');

Route::group(['as'=>'admin.' ,'middleware' => 'auth', 'prefix'=>'admin'], function(){
    // Admin Settings and Login
    Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');
    Route::get('/admin/profile/{id}', 'AdminController@profile')->name('profile');
    Route::post('/admin/update/profile/{id}', 'AdminController@updateProfile')->name('update.profile');
    Route::match(['get', 'post'], '/admin/edit/password', 'AdminController@editPassword')->name('edit.password');
    Route::post('/admin/edit/check-password', 'AdminController@chkUserPassword');

    //Categories
    Route::get('category/create', 'CategoryController@create')->name('category.create');
    Route::get('category/view', 'CategoryController@view')->name('category.view');
    Route::post('category/store', 'CategoryController@store')->name('category.store');
    Route::match(['get','post'],'edit-category/{id}','CategoryController@edit')->name('category.edit');
    Route::match(['get','post'],'delete-category/{id}','CategoryController@delete')->name('category.delete');
    Route::match(['get','post'],'trash-category/{id}','CategoryController@trash')->name('category.trash');

    //Jobs
    Route::match(['get','post'],'job/create','JobController@addJob')->name('job.create');
    Route::match(['get','post'],'job/view-jobs','JobController@viewJobs')->name('job.view');
    Route::match(['get','post'],'edit-job/{id}','JobController@edit')->name('job.edit');
    Route::match(['get','post'],'/delete-job/{id}','JobController@delete')->name('job.delete');
    Route::match(['get','post'],'delete-job-image/{id}','JobController@deleteJobImage')->name('job.image.delete');


    // Route::match(['get','post'],'trash-job/{id}','JobController@trash')->name('job.trash');











});



Route::get('/logout', 'AdminController@logout')->name('admin.logout');


Route::get('/home', 'HomeController@index')->name('home');

// Categories
// Route::group(['as'=>'admin.', 'middleware'=>['auth', 'admin'] , 'prefix'=>'admin'],function(){



// });

app/Job.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Job extends Model
{
  public function category()
    {
        return $this->belongsToMany('App\Category');
    }
}

app/Http/Controllers/JobController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Image;

use App\Category;
use App\Job;
class JobController extends Controller
{
    public function addJob(Request $request){
    	//storing data
    	if ($request->isMethod('post')) {
    		$data =$request->all();
    		// dd($data);
            // if (empty($data['category_id'])){
            //     return redirect()->back()->with('flash_message_error', 'Under Category is missing');
            // }
    		$job = new Job;
    		$job->category_id = $data['category_id'];
            $job->company = $data['company'];

    		$job->title = $data['title'];
    		$job->description = $data['description'];
            $this->validate($request, ['file' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',]);
    		  //upload image
            if($request->hasFile('image')){
                 $image_tmp = Input::file('image');
                if($image_tmp->isValid()){

                    $extension = $image_tmp->getClientOriginalExtension();
                    $filename = rand(111,99999).'.'.$extension;
                    $large_image_path = 'public/adminpanel/uploads/job/large/'.$filename;
                    $small_image_path ='public/adminpanel/uploads/job/small/'.$filename;
                    //Resize images
                    Image::make($image_tmp)->save($large_image_path);
                    // Image::make($image_tmp)->resize(600,600)->save($medium_image_path);
                    Image::make($image_tmp)->resize(300,300)->save($small_image_path);
                    //store image name in products table
                    $job->image = $filename;

                }
            }

    		    		// dd($job->image);

    		$job->opening_job = $data['opening_job'];
    		//dd($job->opening_job);
    		$job->location = $data['location'];
    		 //$job->available_time = $data['available_time'];
    		$job->save();
               return redirect()->back()->with('flash_message', 'Your Job Has Been Successfully Created');

    		


    	}
    	// Categories dropdown start
    	$categories = Category::where(['parent_id'=>0])->get();
    	$categories_dropdown = "<option selected disabled>Select</option>";
    	// dd($categories_dropdown );
    	foreach($categories as $cat){
    		$categories_dropdown .= "<option value ='".$cat->id."'>".$cat->title."</option>";
    		$sub_categories = Category::where(['parent_id'=>$cat->id])->get();
    		foreach( $sub_categories as $sub_cat){
    			$categories_dropdown .= "<option value='".$sub_cat->id."'>&nbsp--&nbsp;".$sub_cat->title.
    			"</option>";
    		}
    	}
                   // Categories dropdown ends


    return view('admin.jobs.create')->with(compact('categories_dropdown'));
    }


     public function viewJobs(Request $request){
        $jobs = Job::get();
        // dd($jobs);
        return view('admin.jobs.view')->with(compact('jobs'));
    }
  public function edit(Request $request,$id=null){
    //Updating data 
    if($request->isMethod('post')){
            $data= $request->all();
// dd($data);
              //upload image
            if($request->hasFile('image')){
                 $image_tmp = Input::file('image');
                if($image_tmp->isValid()){

                    $extension = $image_tmp->getClientOriginalExtension();
                    $filename = rand(111,99999).'.'.$extension;
                    $large_image_path = 'public/adminpanel/uploads/job/large/'.$filename;
                    $small_image_path ='public/adminpanel/uploads/job/small/'.$filename;
                    //Resize images
                    Image::make($image_tmp)->save($large_image_path);
                    // Image::make($image_tmp)->resize(600,600)->save($medium_image_path);
                    Image::make($image_tmp)->resize(300,300)->save($small_image_path);
                    //store image name in products table
                    

                }
            }
            else{
                $filename = $data['current_image'];
            }
              Job::where(['id'=>$id])->update(['category_id'=>$data['category_id'],'title'=>$data['title'],'description'=>$data['description'],'opening_job'=>$data['opening_job'],'location'=>$data['location'],'image'=>$filename]);
 return redirect()->back()->with('flash_message', 'Job Has Been Successfully Updated');
    }
    //Get Job Details
   $jobDetails = Job::where(['id'=>$id])->first();
   // Categories dropdown start
        $categories = Category::where(['parent_id'=>0])->get();
        $categories_dropdown = "<option selected disabled>Select</option>";
        // dd($categories_dropdown );
        foreach($categories as $cat){
            if($cat->id == $jobDetails->category_id){
                $selected="selected";

            }
            else{
                $selected="";
            }
            $categories_dropdown .= "<option value ='".$cat->id."' ".$selected.">".$cat->title."</option>";
            $sub_categories = Category::where(['parent_id'=>$cat->id])->get();
            foreach( $sub_categories as $sub_cat){
                    if($sub_cat->id == $jobDetails->category_id){
                $selected="selected";

            }
            else{
                $selected="";
            }
                $categories_dropdown .= "<option value='".$sub_cat->id."' ".$selected.">&nbsp--&nbsp;".$sub_cat->title.
                "</option>";
            }
        }
           // Categories dropdown ends

   return view('admin.jobs.edit', compact('jobDetails', 'categories_dropdown'));
        
}
     public function delete($id=null){
                
                    Job::where(['id'=>$id])->delete();
                    return redirect()->back()->with('flash_message','Job Has Been Deleted Successfully');
                
             }

public function deleteJobImage($id = null){
    Job::where(['id'=>$id])->update(['image'=>'']);
     return redirect()->back()->with('flash_message', 'Job Image Has Been Successfully Deleted');

    }
    // public function delete($id = null){
    // Job::where(['id'=>$id])->delete();
    //  return redirect()->back()->with('flash_message', 'Job Image Has Been Successfully Deleted');

    // }

}

resources/views/admin/jobs/create.blade.php
@extends('admin.layouts.admin_design')

@section('title')
    <title>Jobs{{ config('app.name', 'Laravel') }}</title>
@endsection

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
               Add Jobs
            </h1>
             <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}"><i class="iconsmind-Library"></i></a></li>
                <li class="breadcrumb-item"><a href="javascript:">Admin</a></li>
                <li class="breadcrumb-item active">Add Jobs</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
         

            <!-- Basic Forms -->
            <div class="box box-solid box-info">
                <div class="box-header with-border">
                    <h6 class="box-subtitle text-white">Job Details</h6>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="col">
                            <form action="{{route('admin.job.create')}}" method="POST" enctype="multipart/form-data">
                                @csrf
                                           <div class="form-group">
                                    <h5>Under Category<span class="text-danger">*</span></h5>
                <div class="controls">
                  <select name="category_id"  id="category_id" class="form-control" aria-invalid="false" data-validation-required-message="Category Level is Required" >
                  <?php echo "$categories_dropdown"; ?>
                  </select>
                </div>
              </div>
               <div class="form-group">
                                    <h5>Company<span class="text-danger">*</span></h5>
                                    <div class="controls">
                                        <input type="text" name="company" id="company" class="form-control" data-validation-required-message="Company Name is Required" > </div>
                                </div>
                                <div class="form-group">
                                    <h5>Job Name<span class="text-danger">*</span></h5>
                                    <div class="controls">
                                        <input type="text" name="title" id="title" class="form-control" data-validation-required-message="Name Field is Required" > </div>
                                </div>
                     
                                <div class="form-group">
                        <h5>Description <span class="text-danger">*</span></h5>
                        <div class="controls">
                            <textarea name="description" id="description" class="form-control" placeholder="Textarea text" data-validation-required-message="Description Field is Required"></textarea>
                        <div class="help-block"></div></div>
                    </div>
                        <div class="form-group">
                                    <h5>Image</h5>
                                    <div class="controls">
                                        <input type="file" name="image" id="image" class="form-control"> </div>
                                    <br>    
                                </div>

                                
                                <div class="form-group validate">
                        <h5>Opening Jobs <span class="text-danger">*</span></h5>
                        <div class="controls">
                            <input type="text" name="opening_job" id="opening_job" class="form-control" data-validation-containsnumber-regex="(\d)+" data-validation-containsnumber-message="No Characters Allowed, Only Numbers" data-validation-required-message="Opening Job Field is Required" aria-invalid="false"> <div class="help-block"></div></div>
                    </div>
                 
                    <div class="form-group">
                        <h5>Location<span class="text-danger">*</span></h5>
                        <div class="controls">
                            <textarea name="location" id="location" class="form-control" placeholder="Textarea text" data-validation-required-message="Location Field is Required"></textarea>
                        <div class="help-block"></div></div>
                    </div>
                       <div class="form-group">
                        <h5>Available Time<span class="text-danger">*</span></h5>
                        <div class="controls">
                            <select name="available_time" id="available_time" required="" class="form-control" aria-invalid="false" data-validation-required-message="Available Time Field is Required">
                                <option value="">Select Time Available</option>
                                <option value="Full Time">Full Time</option>
                                <option value="Part Time">Part Time</option>
                            </select>
                        <div class="help-block"></div></div>
                    </div>
                

                                <div class="text-xs-right">
                                    <button type="submit" class="btn btn-info" id="btn">Add Job</button>
                                </div>
                            </form>

                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

@section('styles')
<link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote-lite.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
@endsection

@section('scripts')
    <!-- Form validator JavaScript -->
    <script src="{{asset('public/adminpanel/js/pages/validation.js')}}"></script>
    <script>
        ! function(window, document, $) {
            "use strict";
            $("input,select,textarea").not("[type=submit]").jqBootstrapValidation();
        }(window, document, jQuery);
    </script>


    <script type="text/javascript">
        @if(session('flash_message'))
        swal("Success!", "{!! session('flash_message') !!}", "success")
        @endif
    </script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote-lite.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

 <script>
      $('#description').summernote({
        tabsize: 2,
        height: 100
      });
    </script> 

   <script>
$(document).ready(function(){
  var count = 0;
$("#btn").click(function() {
    count++;
    $("#counter").html("Jobs: "+count);
}
  });
  
</script>
@endsection

resources/views/admin/jobs/edit.blade.php
@extends('admin.layouts.admin_design')
@section('title')
<title>Jobs{{ config('app.name', 'Laravel') }}</title>
@endsection
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
        Edit Jobs
        </h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}"><i class="iconsmind-Library"></i></a></li>
            <li class="breadcrumb-item"><a href="javascript:">Admin</a></li>
            <li class="breadcrumb-item active">Edit Jobs</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Basic Forms -->
        <div class="box box-solid box-info">
            <div class="box-header with-border">
                <h6 class="box-subtitle text-white">Job Details</h6>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    <div class="col">
                        <form action="{{route('admin.job.edit',$jobDetails->id)}}" method="POST" enctype="multipart/form-data" name="edit" id="edit">
                            @csrf
                            <div class="form-group">
                                <h5>Under Category<span class="text-danger">*</span></h5>
                                <div class="controls">
                                    <select name="category_id"  id="category_id" class="form-control" aria-invalid="false" data-validation-required-message="Category Level is Required" >
                                        <?php echo "$categories_dropdown"; ?>
                                    </select>
                                </div>
                            </div>
                             <div class="form-group">
                                <h5>Company<span class="text-danger">*</span></h5>
                                <div class="controls">
                                <input type="text" name="company" id="company" class="form-control" data-validation-required-message="Name Field is Required" value="{{ $jobDetails->title}}" > </div>
                            </div>
                            <div class="form-group">
                                <h5>Job Name<span class="text-danger">*</span></h5>
                                <div class="controls">
                                <input type="text" name="title" id="title" class="form-control" data-validation-required-message="Name Field is Required" value="{{ $jobDetails->title}}" > </div>
                            </div>
                            <div class="form-group">
                                <h5>Description <span class="text-danger">*</span></h5>
                                <div class="controls">
                                    <textarea name="description" id="description" class="form-control" placeholder="Textarea text" data-validation-required-message="Description Field is Required">{{ $jobDetails->description}}</textarea>
                                    <div class="help-block"></div>
                                </div>
                            </div>
                            <div class="form-group">
                                <h5>Image</h5>
                                <div class="controls">
                                    <input type="file" name="image" id="image" class="">
                                    <input type="hidden" name="current_image" value="{{$jobDetails->image}}">
                                    {{-- //no empty Image --}}
                                    @if(!empty($jobDetails->image))
                                    <img style="height:50px;" src="{{asset('public/adminpanel/uploads/job/small/'.$jobDetails->image)}} " alt=""> | <a href="{{route('admin.job.image.delete', $jobDetails->id)}}">Delete</a>
                                    @endif
                                </div>
                                <br>
                            </div>
                            <div class="form-group validate">
                                <h5>Opening Jobs <span class="text-danger">*</span></h5>
                                <div class="controls">
                                    <input type="text" name="opening_job" id="opening_job" class="form-control" data-validation-containsnumber-regex="(\d)+" data-validation-containsnumber-message="No Characters Allowed, Only Numbers" aria-invalid="false" value="{{ $jobDetails->opening_job}}"> <div class="help-block"></div></div>
                                </div>
                                <div class="form-group">
                                    <h5>Location<span class="text-danger">*</span></h5>
                                    <div class="controls">
                                        <textarea name="location" id="location" class="form-control" placeholder="Textarea text" data-validation-required-message="Description Field is Required">{{ $jobDetails->location}}</textarea>
                                        <div class="help-block"></div></div>
                                    </div>
                                    {{-- <div class="form-group">
                                        <h5>Available Time<span class="text-danger">*</span></h5>
                                        <div class="controls">
                                            <select name="available_time" id="available_time" required="" class="form-control" aria-invalid="false" value="{{ $jobDetails->title}}">
                                                <option value="">Select Time Available</option>
                                                <option value="Full Time">Full Time</option>
                                                <option value="Part Time">Part Time</option>
                                            </select>
                                            <div class="help-block"></div></div>
                                        </div> --}}
                                        <div class="text-xs-right">
                                            <button type="submit" class="btn btn-info">Edit Job</button>
                                        </div>
                                    </form>
                                </div>
                                <!-- /.col -->
                            </div>
                            <!-- /.row -->
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </section>
                <!-- /.content -->
            </div>
            <!-- /.content-wrapper -->
            @endsection
            @section('scripts')
            <!-- Form validator JavaScript -->
            <script src="{{asset('public/adminpanel/js/pages/validation.js')}}"></script>
            <script>
            ! function(window, document, $) {
            "use strict";
            $("input,select,textarea").not("[type=submit]").jqBootstrapValidation();
            }(window, document, jQuery);
            </script>
            <script type="text/javascript">
            @if(session('flash_message'))
            swal("Success!", "{!! session('flash_message') !!}", "success")
            @endif
            </script>
            @endsection

resources/views/admin/jobs/view.blade.php
@extends('admin.layouts.admin_design')

@section('title')
<title>All Category- {{ config('app.name', 'Laravel') }}</title>
@endsection

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
<!-- Content Header (Page header) -->
<section class="content-header">
<h1>
All Jobs
</h1>
<ol class="breadcrumb">
<li class="breadcrumb-item"><a href="#"><i class="iconsmind-Library"></i></a></li>
<li class="breadcrumb-item"><a href="#">Tables</a></li>
<li class="breadcrumb-item active">All Jobs</li>
</ol>
</section>

<!-- Main content -->
<section class="content">
<div class="row">
<div class="col-12">
<div class="box box-solid box-primary">
<div class="box-header with-border">
<h4 class="box-title">See All Jobs</h4>
</div>
<!-- /.box-header -->
<div class="box-body">
<div class="table-responsive">
<table id="example" class="table table-bordered table-hover display nowrap margin-top-10 w-p100">
<thead>
<tr>
<th>Id</th>
<th>Company</th>
<th>Job</th>
<th>Description</th>
{{-- <th>Category Name</th> --}}

<th>Cat Id</th>
<th>Image</th>
<th>Seats</th>
<th>Location</th>
{{-- <th>Time</th> --}}
<th>Actions</th>
</tr>
</thead>
<tbody>
@foreach($jobs as $job)
<tr>
<td>{{$job->id}}</td>
<td>{{$job->company}}</td>

<td>{{$job->title}}</td>
<td>{{$job->description}}</td>
{{-- <td>{{$job->category_name }}</td> --}}
<td>{{$job->category_id}}</td>
<td>
@if(!empty($job->image))
<img src="{{asset('public/adminpanel/uploads/job/small/'.$job->image)}}" alt="" style="width: 50px;">
@endif

</td>

<td>{{$job->opening_job}}</td>
<td>{{$job->location}}</td>
{{-- <td>{{$job->availabe_time}}</td> --}}

<td>
<a href="{{ route('admin.job.edit',$job->id)}}"><button type="button" class="btn btn-info mb-5"><i class="fa fa-pencil"></i></button></a> 
{{--  <a href="{{ route('admin.job.trash',$job->id)}}"><button type="button" class="btn btn-warning mb-5">Trash</button></a> --}} 

<a href="javascript:" rel="{{$job->id}}" rel1="delete-job" class="btn btn-danger btn-xs deleteRecord" data-toggle="tooltip" title="Delete" data-original-title="Delete">
<i class="fa fa-trash"></i>
</a>


</td>

</tr>
@endforeach

</tbody>                  
</table>
</div>              
</div>
<!-- /.box-body -->
</div>
<!-- /.box -->          
</div>
<!-- /.col -->
</div>
<!-- /.row -->
</section>
<!-- /.content -->
</div>
<!-- /.content-wrapper -->
</div>
<!-- ./wrapper -->
@endsection


@section('scripts')
<!-- Form validator JavaScript -->
<script type="text/javascript">
        @if(session('flash_message'))
            swal("Success!", "{!! session('flash_message') !!}", "success")
        @endif
    </script>
<script>
       $(".deleteRecord").click(function(){
           var id = $(this).attr('rel');
           var deleteFunction = $(this).attr('rel1');
           // alert(deleteFunction);
           swal({
                   title: "Are You Sure?",
                   text: "You will not be able to recover this record again",
                   type: "warning",
                   showCancelButton: true,
                   confirmButtonClass: "btn-danger",
                   confirmButtonText: "Yes, Delete it!"
               },
               function(){
                   window.location.href="/planet-jobs/public/admin/"+deleteFunction+"/"+id;
               });

       });
   </script>

@endsection