routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/', 'IndexController@index');
Route::match(['get', 'post'], '/adminLogin', 'AdminController@login')->name('admin.login');

//Password reset routes
Route::post('admin/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::get('admin/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::post('admin/password/reset', 'Auth\ResetPasswordController@reset')->name('admin.password.update');
Route::get('admin/password/reset/{token}','Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');

Route::group(['as'=>'admin.' ,'middleware' => 'auth', 'prefix'=>'admin'], function(){
    // Admin Settings and Login
    Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');
    Route::get('/admin/profile/{id}', 'AdminController@profile')->name('profile');
    Route::post('/admin/update/profile/{id}', 'AdminController@updateProfile')->name('update.profile');
    Route::match(['get', 'post'], '/admin/edit/password', 'AdminController@editPassword')->name('edit.password');
    Route::post('/admin/edit/check-password', 'AdminController@chkUserPassword');

    //Categories
    Route::get('category/create', 'CategoryController@create')->name('category.create');
    Route::get('category/view', 'CategoryController@view')->name('category.view');
    Route::post('category/store', 'CategoryController@store')->name('category.store');
    Route::match(['get','post'],'edit-category/{id}','CategoryController@edit')->name('category.edit');
    Route::match(['get','post'],'delete-category/{id}','CategoryController@delete')->name('category.delete');
    Route::match(['get','post'],'trash-category/{id}','CategoryController@trash')->name('category.trash');

    //Jobs
    Route::match(['get','post'],'job/create','JobController@addJob')->name('job.create');
    Route::match(['get','post'],'job/view-jobs','JobController@viewJobs')->name('job.view');
    Route::match(['get','post'],'edit-job/{id}','JobController@edit')->name('job.edit');
    Route::match(['get','post'],'/delete-job/{id}','JobController@delete')->name('job.delete');
    Route::match(['get','post'],'delete-job-image/{id}','JobController@deleteJobImage')->name('job.image.delete');


    // Route::match(['get','post'],'trash-job/{id}','JobController@trash')->name('job.trash');











});



Route::get('/logout', 'AdminController@logout')->name('admin.logout');


Route::get('/home', 'HomeController@index')->name('home');

// Categories
// Route::group(['as'=>'admin.', 'middleware'=>['auth', 'admin'] , 'prefix'=>'admin'],function(){



// });

resources/views/admin/layouts/admin_design.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    @include('admin.layouts.head')
</head>

<body class="hold-transition skin-green-light sidebar-mini">
<div class="wrapper">
<div class="container_fluid">
@include('admin.layouts.header')


<!-- Left side column. contains the logo and sidebar -->
@include('admin.layouts.sidebar')


<!-- Content Wrapper. Contains page content -->
@yield('content')
<!-- /.content-wrapper -->

@include('admin.layouts.footer')

<!-- Control Sidebar -->
    <!-- /.control-sidebar -->

    <!-- Add the sidebar's background. This div must be placed immediately after the control sidebar -->
    <div class="control-sidebar-bg"></div>

</div>
<!-- ./wrapper -->



@include('admin.layouts.script')

</body>
</html>

resources/views/admin/layouts/footer.blade.php
<footer class="main-footer">

    &copy; <?php echo date('Y'); ?> <a href="https://onlinezeal.com/" target="_blank">Next Aussie Tech</a>. All Rights Reserved.
</footer>

resources/views/admin/layouts/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<meta name="csrf-token" content="{{ csrf_token() }}">

<link rel="icon" href="{{asset('public/adminpanel/images/fab.png')}}">

@yield('title')
<!-- Bootstrap 4.0-->
<link rel="stylesheet" href="{{asset('public/adminpanel/assets/vendor_components/bootstrap/dist/css/bootstrap.css')}}">
	{{-- <link rel="stylesheet" href="{{asset('public/adminpanel/assets/vendor_components/bootstrap/dist/css/bootstrap.min.css')}}"> --}}

<!-- Bootstrap extend-->
<link rel="stylesheet" href="{{asset('public/adminpanel/css/bootstrap-extend.css')}}">

<!-- theme style -->
<link rel="stylesheet" href="{{asset('public/adminpanel/css/master_style.css')}}">

<!-- NeoX Admin skins -->
<link rel="stylesheet" href="{{asset('public/adminpanel/css/skins/_all-skins.css')}}">


<link href="{{asset('public/adminpanel/assets/vendor_components/sweetalert/sweetalert.css')}}" rel="stylesheet" type="text/css">

@yield('styles')

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

resources/views/admin/layouts/header.blade.php
<header class="main-header">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Logo -->
    <a href="{{route('admin.dashboard')}}" class="logo">
        <!-- mini logo -->
        <b class="logo-mini">
            <span class="light-logo"><img src="{{asset('public/adminpanel/images/login-top.png')}}" alt="logo" style="height: 5vh !important;"></span>
            <span class="dark-logo"><img src="{{asset('public/adminpanel/images/login-top.png')}}" alt="logo" style="height: 5vh !important;"></span>
        </b>

    </a>
    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top">

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

                <li class="search-box">
                    <a class="nav-link hidden-sm-down" href="javascript:void(0)"><i class="iconsmind-Magnifi-Glass2"></i></a>
                    <form class="app-search" style="display: none;">
                        <input type="text" class="form-control" placeholder="Search &amp; enter"> <a class="srh-btn"><i class="ti-close"></i></a>
                    </form>
                </li>
                <!-- Notifications -->
                <li class="dropdown notifications-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="iconsmind-Bell"></i>
                    </a>
                    <ul class="dropdown-menu scale-up">
                        <li class="header">You have 7 notifications</li>
                        <li>
                            <!-- inner menu: contains the actual data -->
                            <ul class="menu inner-content-div">
                                <li>
                                    <a href="#">
                                        <i class="fa fa-users text-aqua"></i> Curabitur id eros quis nunc suscipit blandit.
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-warning text-yellow"></i> Duis malesuada justo eu sapien elementum, in semper diam posuere.
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-users text-red"></i> Donec at nisi sit amet tortor commodo porttitor pretium a erat.
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-shopping-cart text-green"></i> In gravida mauris et nisi
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-user text-red"></i> Praesent eu lacus in libero dictum fermentum.
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-user text-red"></i> Nunc fringilla lorem
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-user text-red"></i> Nullam euismod dolor ut quam interdum, at scelerisque ipsum imperdiet.
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer"><a href="#">View all</a></li>
                    </ul>
                </li>
                <!-- User Account-->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="iconsmind-User"></i>
                    </a>
                    <?php
                    $current_user = Auth::user();
                    ?>
                    <ul class="dropdown-menu scale-up">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="{{asset($current_user->image)}}" class="float-left rounded-circle" alt="User Image">
                            <p>
                                {{$current_user->name}}
                                <small class="mb-5">{{$current_user->email}}</small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <li class="user-body">
                            <div class="row no-gutters">
                                <div class="col-12 text-left">
                                    <a href="{{route('admin.profile', $current_user->id)}}"><i class="ion ion-person"></i> My Profile</a>
                                </div>
                                <div class="col-12 text-left">
                                    <a href="#"><i class="ion ion-email-unread"></i> Inbox</a>
                                </div>
                                <div class="col-12 text-left">
                                    <a href="#"><i class="ion ion-settings"></i> Setting</a>
                                </div>
                                <div role="separator" class="divider col-12"></div>
                                <div class="col-12 text-left">
                                    <a href="{{route('admin.edit.password')}}"><i class="ti-settings"></i> Password Setting</a>
                                </div>
                                <div role="separator" class="divider col-12"></div>
                                <div class="col-12 text-left">
                                    <a href="{{route('admin.logout')}}"><i class="fa fa-power-off"></i> Logout</a>
                                </div>
                            </div>
                            <!-- /.row -->
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->

            </ul>
        </div>
    </nav>
</header>

resources/views/admin/layouts/script.blade.php
<!-- jQuery 3 -->
<script src="{{asset('public/adminpanel/assets/vendor_components/jquery/dist/jquery.js')}}"></script>

<!-- popper -->
<script src="{{asset('public/adminpanel/assets/vendor_components/popper/dist/popper.min.js')}}"></script>

<!-- Bootstrap 4.0-->
<script src="{{asset('public/adminpanel/assets/vendor_components/bootstrap/dist/js/bootstrap.js')}}"></script>

<!-- Slimscroll -->
<script src="{{asset('public/adminpanel/assets/vendor_components/jquery-slimscroll/jquery.slimscroll.js')}}"></script>

<!-- FastClick -->
<script src="{{asset('public/adminpanel/assets/vendor_components/fastclick/lib/fastclick.js')}}"></script>

<!-- apexcharts -->
<script src="{{asset('public/adminpanel/assets/vendor_components/apexcharts-bundle/irregular-data-series.js')}}"></script>
<script src="{{asset('public/adminpanel/assets/vendor_components/apexcharts-bundle/dist/apexcharts.js')}}"></script>

<!-- NeoX Admin App -->
<script src="{{asset('public/adminpanel/js/template.js')}}"></script>

<!-- NeoX Admin dashboard demo (This is only for demo purposes) -->
<script src="{{asset('public/adminpanel/js/pages/dashboard3.js')}}"></script>

<!-- NeoX Admin for demo purposes -->
<script src="{{asset('public/adminpanel/js/demo.js')}}"></script>

<script src="{{asset('public/adminpanel/assets/vendor_components/sweetalert/sweetalert.min.js')}}"></script>
<script src="{{asset('public/adminpanel/assets/vendor_components/sweetalert/jquery.sweet-alert.custom.js')}}"></script>

<!-- DataTables -->
<script src="{{asset('public/adminpanel/assets/vendor_components/datatable/datatables.min.js')}}"></script>

<!-- Form -->
<!-- DataTables -->
 <script src="{{asset('public/adminpanel/js/pages/data-table.js')}}"></script>
 <script src="{{asset('public/adminpanel/js/demo.js')}}"></script>
 <script src="{{asset('public/adminpanel/js/template.js')}}"></script>

  



@yield('scripts')

resources/views/admin/layouts/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar-->
    <section class="sidebar">

        <!-- sidebar menu-->
        <ul class="sidebar-menu" data-widget="tree">


            <li class="treeview">
                <a href="#">
                    <i class="iconsmind-Posterous"></i>
                    <span>Category</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('admin.category.create')}}"><i class="iconsmind-Add"></i>Add Category</a></li>
                    <li><a href="{{route('admin.category.view')}}"><i class="iconsmind-Add"></i>All Categories</a></li>
                    <li><a href=""><i class="iconsmind-Add"></i>Trashed Categories</a></li>

                </ul>

            </li>
             <li class="treeview">
                <a href="#">
                    <i class="iconsmind-Posterous"></i>
                    <span>Job</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('admin.job.create')}}"><i class="iconsmind-Add"></i>Add Jobs</a></li>
                    <li><a href="{{route('admin.job.view')}}"><i class="iconsmind-Add"></i>All Jobs</a></li>
                    <li><a href=""><i class="iconsmind-Add"></i>Trashed Jobs</a></li>

                </ul>

            </li>

        </ul>


    </section>
</aside>