routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/', 'IndexController@index');
Route::match(['get', 'post'], '/adminLogin', 'AdminController@login')->name('admin.login');

//Password reset routes
Route::post('admin/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::get('admin/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::post('admin/password/reset', 'Auth\ResetPasswordController@reset')->name('admin.password.update');
Route::get('admin/password/reset/{token}','Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');

Route::group(['as'=>'admin.' ,'middleware' => 'auth', 'prefix'=>'admin'], function(){
    // Admin Settings and Login
    Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');
    Route::get('/admin/profile/{id}', 'AdminController@profile')->name('profile');
    Route::post('/admin/update/profile/{id}', 'AdminController@updateProfile')->name('update.profile');
    Route::match(['get', 'post'], '/admin/edit/password', 'AdminController@editPassword')->name('edit.password');
    Route::post('/admin/edit/check-password', 'AdminController@chkUserPassword');

    //Categories
    Route::get('category/create', 'CategoryController@create')->name('category.create');
    Route::get('category/view', 'CategoryController@view')->name('category.view');
    Route::post('category/store', 'CategoryController@store')->name('category.store');
    Route::match(['get','post'],'edit-category/{id}','CategoryController@edit')->name('category.edit');
    Route::match(['get','post'],'delete-category/{id}','CategoryController@delete')->name('category.delete');
    Route::match(['get','post'],'trash-category/{id}','CategoryController@trash')->name('category.trash');

    //Jobs
    Route::match(['get','post'],'job/create','JobController@addJob')->name('job.create');
    Route::match(['get','post'],'job/view-jobs','JobController@viewJobs')->name('job.view');
    Route::match(['get','post'],'edit-job/{id}','JobController@edit')->name('job.edit');
    Route::match(['get','post'],'/delete-job/{id}','JobController@delete')->name('job.delete');
    Route::match(['get','post'],'delete-job-image/{id}','JobController@deleteJobImage')->name('job.image.delete');


    // Route::match(['get','post'],'trash-job/{id}','JobController@trash')->name('job.trash');











});



Route::get('/logout', 'AdminController@logout')->name('admin.logout');


Route::get('/home', 'HomeController@index')->name('home');

// Categories
// Route::group(['as'=>'admin.', 'middleware'=>['auth', 'admin'] , 'prefix'=>'admin'],function(){



// });

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //  protected $fillable = [
    //     'title', 'description', 'image',
    // ];
     // protected $guarded = [];
    protected $fillable = array('title', 'description', 'image');

    public function job(){
         return $this->belongsToMany('App\Job');
    }
    public function rules()
    {
        return [
            'image' => 'required | mimes:jpeg,jpg,png | max:5000',

        ];
    }
}

app/Http/Controllers/CategoryController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Category;
use Illuminate\Support\Facades\Input;
use Image;

class CategoryController extends Controller
{
public function view()
{
$categories = Category::paginate(6);
return view('admin.categories.view', compact('categories'));
}
public function create()
{
$categories =Category::all();
$levels = Category::where(['parent_id'=>0])->get();

return view('admin.categories.create', compact('categories','levels'));
}
public function store(Request $request)
{

if($request->isMethod('post')){
            //echo "<pre>"; print_r($data); die;
      $data = $request->all();
       $category = new Category;
      // dd($request);
      // $rule = $category->rules();
      // $check = $request->validate($rule);
     
      //dd($check);
     
      $category->title = ucwords(strtolower($data['title']));
      $category->parent_id = $data['parent_id'];
      if(empty($data['description'])){
       $category->description = "";
     } else {
       $category->description = $data['description'];
     }
         //Intervention image
     if($request->hasFile('image')){
      $image_tmp = Input::file('image');
      if($image_tmp->isValid()){
       $extension = $image_tmp->getClientOriginalExtension();
       $filename = rand(111,99999).'.'.$extension;
       $large_image_path = 'public/adminpanel/uploads/category/large/'.$filename;
       $small_image_path = 'public/adminpanel/uploads/category/small/'.$filename;
                     //Resize images
       Image::make($image_tmp)->save($large_image_path);
       Image::make($image_tmp)->resize(300,300)->save($small_image_path);
       //store image name in products table
       $category->image = $filename;
     }
   }
        // $category->icon = $data['icon'];

   $category->save();
   return redirect()->back()->with('flash_message', 'Your Category Has Been Successfully Created');
  }
  }



  public function edit(Request $request,$id=null){
   //echo"test";die;
    // dd($request);
    if($request->isMethod('post')){
     $data = $request->all();
             //echo "<pre>"; print_r($data); die;
                //dd('$data');
       Category::where(['id'=>$id])->update(['title'=>$data['title'],'description'=>$data['description']]);
       return redirect('admin/category/index')->with('flash_message', 'Successfully Updated');
     } 
              //Edit
     $categoryDetails= Category::where(['id'=>$id])->first();
           // dd($categoryDetails);
     $levels = Category::where(['parent_id'=>0])->get();
     return view('admin.categories.edit')->with(compact('categoryDetails', 'levels'));
    }


    public function delete( Request $request, $id=null){
      if(!empty($id)){
        Category::where(['id'=>$id])->delete();
        return redirect('admin/category/index')->with('flash_message', 'Successfully Deleted');
      }
    }
     public function trash(Category $category)
    {
        if($category->delete()){
            return back()->with('message','Category Successfully Trashed!');
        }else{
            return back()->with('message','Error Deleting Record');
        }
    }
    }
   

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.admin_design')

@section('title')
    <title>Add Category- {{ config('app.name', 'Laravel') }}</title>
@endsection

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
               Add Category
            </h1>
             <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}"><i class="iconsmind-Library"></i></a></li>
                <li class="breadcrumb-item"><a href="javascript:">Admin</a></li>
                <li class="breadcrumb-item active">Add Category</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
         

            <!-- Basic Forms -->
            <div class="box box-solid box-info">
                <div class="box-header with-border">
                    <h6 class="box-subtitle text-white">Category Details</h6>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="col">
                            <form action="{{route('admin.category.store')}}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group">
                                    <h5>Category Name<span class="text-danger">*</span></h5>
                                    <div class="controls">
                                        <input type="text" name="title" id="title" class="form-control" data-validation-required-message="Name Field is Required" > </div>
                                </div>
                                <div class="form-group">
                                    <h5>Category Level<span class="text-danger">*</span></h5>
                <div class="controls">
                  <select name="parent_id"  id="parent_id" class="form-control" aria-invalid="false" data-validation-required-message="Category Level is Required" >
                    <option value="0">Main Category </option>
                    @foreach($levels as $val)
                      <option value="{{ $val->id }}">{{ $val->title}}</option>
                    @endforeach
                  </select>
                </div>
              </div>
                                <div class="form-group">
                        <h5>Description <span class="text-danger">*</span></h5>
                        <div class="controls">
                            <textarea name="description" id="description" class="form-control" placeholder="Textarea text" data-validation-required-message="Description Field is Required"></textarea>
                        <div class="help-block"></div></div>
                    </div>

                                <div class="form-group">
                                    <h5>Image</h5>
                                    <div class="controls">
                                        <input type="file" name="image" id="image" class="form-control"> </div>
                                    <br>    
                                </div>
                               {{--  <div class="form-group">
                                    <h5>Icon</h5>
                                    <div class="controls">
                                        <input type="file" name="icon" id="icon" class="form-control"> </div>
                                    <br>    
                                </div>
 --}}
                                <div class="text-xs-right">
                                    <button type="submit" class="btn btn-info">Add Category</button>
                                </div>
                            </form>

                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection


@section('styles')
<link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote-lite.css" rel="stylesheet">

@endsection

@section('scripts')
    <!-- Form validator JavaScript -->
    <script src="{{asset('public/adminpanel/js/pages/validation.js')}}"></script>
    <script>
        ! function(window, document, $) {
            "use strict";
            $("input,select,textarea").not("[type=submit]").jqBootstrapValidation();
        }(window, document, jQuery);
    </script>


    <script type="text/javascript">
        @if(session('flash_message'))
        swal("Success!", "{!! session('flash_message') !!}", "success")
        @endif
    </script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote-lite.js"></script>
 <script>
      $('#description').summernote({
        tabsize: 2,
        height: 100
      });
    </script>   

  
@endsection

resources/views/admin/categories/edit.blade.php
    @extends('admin.layouts.admin_design')

    @section('title')
    <title>Edit Category {{ config('app.name', 'Laravel') }}</title>
    @endsection

    @section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
         Add Category
     </h1>
     <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}"><i class="iconsmind-Library"></i></a></li>
        <li class="breadcrumb-item"><a href="javascript:">Admin</a></li>
        <li class="breadcrumb-item active">Edit Category</li>
    </ol>
    </section>

    <!-- Main content -->
    <section class="content">
    <!-- Basic Forms -->
    <div class="box box-solid box-info">
        <div class="box-header with-border">
            <h6 class="box-subtitle text-white">Category Details</h6>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="row">
                <div class="col">
                    <form action="{{route('admin.category.edit',$categoryDetails->id)}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <h5>Category Name<span class="text-danger">*</span></h5>
                            <div class="controls">
                                <input type="text" name="title" id="title" class="form-control" data-validation-required-message="Name Field is Required" value="{{ $categoryDetails->title}}"> </div>
                            </div>
                            <div class="form-group">
                                <h5>Category Level<span class="text-danger">*</span></h5>
                                <div class="controls">
                                  <select name="parent_id"  id="parent_id" class="form-control" aria-invalid="false" data-validation-required-message="Category Level is Required" value="{{ $categoryDetails->parent_id}}">
                                    <option value="0">Main Category </option>
                                    @foreach($levels as $val)
                                    <option value="{{ $val->id }}">{{ $val->title}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <h5>Description <span class="text-danger">*</span></h5>
                            <div class="controls">
                                <textarea name="description" id="description" class="form-control"  data-validation-required-message="Description Field is Required">{{$categoryDetails->description}}</textarea>
                                <div class="help-block"></div></div>
                            </div>

                        <div class="form-group">
                                <h5>Image</h5>
                                <div class="controls">
                                    <input type="file" name="image" class="form-control">{{ $categoryDetails->image}}</div>
                                    <br>    
                                </div>
                                {{-- <div class="form-group">
                                <h5>Icon</h5>
                                <div class="controls">
                                    <input type="file" name="image" class="form-control">{{ $categoryDetails->icon}}</div>
                                    <br>    
                                </div> --}}
                               
                              <div class="text-xs-right">
                                <button type="submit" class="btn btn-info">Edit Category</button>
                            </div>
                        </form>

                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    @endsection


    @section('scripts')
    <!-- Form validator JavaScript -->
    <script src="{{asset('public/adminpanel/js/pages/validation.js')}}"></script>
    <script>
    ! function(window, document, $) {
        "use strict";
        $("input,select,textarea").not("[type=submit]").jqBootstrapValidation();
    }(window, document, jQuery);
    </script>


    <script type="text/javascript">
    @if(session('flash_message'))
    swal("Success!", "{!! session('flash_message') !!}", "success")
    @endif
    </script>
    @endsection

resources/views/admin/categories/view.blade.php
  @extends('admin.layouts.admin_design')

  @section('title')
      <title>All Category- {{ config('app.name', 'Laravel') }}</title>
  @endsection

  @section('content')
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          All Categories
        </h1>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#"><i class="iconsmind-Library"></i></a></li>
          <li class="breadcrumb-item"><a href="#">Tables</a></li>
          <li class="breadcrumb-item active">All Categories</li>
        </ol>
      </section>

      <!-- Main content -->
      <section class="content">
        <div class="row">
          <div class="col-12">
            <div class="box box-solid box-primary">
              <div class="box-header with-border">
                <h4 class="box-title">See All Categories</h4>
            </div>
              <!-- /.box-header -->
              <div class="box-body">
                  <div class="table-responsive">
                    <table id="example" class="table table-bordered table-hover display nowrap margin-top-10 w-p100">
                      <thead>
                          <tr>
                              <th>Category Id</th>
                              <th>Name</th>
                              <th>Description</th>
                              <th>Parent_Id</th>
                              {{-- <th>Image</th> --}}
                              

                              <th>Actions</th>
                          </tr>
                      </thead>
                      <tbody>
                          @foreach($categories as $category)
                          <tr>
                              <td>{{$category->id}}</td>
                              <td>{{$category->title}}</td>
                              <td>{!! $category->description !!}</td>
                              <td>{{$category->parent_id}}</td>
                              {{-- <td>
                              @if(!empty($category->image))
                              <img src="{{asset('public/adminpanel/uploads/category/small/'.$category->image)}}" alt="" style="width: 50px;">
                               @endif
                            </td> --}} 

                             <td>
                                  <a href="{{ route('admin.category.edit',$category->id)}}"><button type="button" class="btn btn-info mb-5"> 
                                    <i class="fa fa-pencil"> </i></button></a>
                                  {{-- <a href="{{ route('admin.category.trash',$category->id)}}"><button type="button" class="btn btn-warning mb-5"><i class="fa fa-trash-o"> </i></button></a> --}}
                                  <a href="{{ route('admin.category.delete',$category->id)}}" id="delCat"><button type="button" class="btn btn-danger mb-5"><i class="fa fa-trash-o"> </i></button></a></td>
                             

                          </tr>
                          @endforeach
                         
                      </tbody>                  
                  </table>
                  </div>              
              </div>
              <!-- /.box-body -->
            </div>
            <!-- /.box -->          
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
  </div>
  <!-- ./wrapper -->
  @endsection


  @section('scripts')
      <script type="text/javascript">
          @if(session('flash_message'))
          swal("Success!", "{!! session('flash_message') !!}", "success")
          @endif
        $("#delCat").click(function(){
          if(confirm('Are you sure you want to delete this category?')){
            return true;
          }
          return false;
        });
      </script>
  @endsection